version: '3.7'

services:
  db:
    image: postgres
    ports:
      - "5440:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: onlyfordev

  app:
    image: awsb-soccer
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "5173:5173"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres

